### ISSUE TITLE
Update to latest version 1.4.1

### ISSUE THREAD

**Issue by cmourizard** [dduportal-dockerfiles/docker-compose#19]
Hello the maintainer team,

They are any reasons (expect of your time of course :-)) that you didn't update this container to the latest version of docker-compose 1.4.1?

Thanks,

**Comment by dduportal** [comment]
Hello @cmourizard  !

Thank you for reporting :)

Note that since i'm alone to maintain this, and not related to Docker, you've got it right : time problem :)

Here is the PR just merged : https://github.com/dduportal-dockerfiles/docker-compose/pull/20

It embed compose 1.4.2 (recently released). Wait some minute the time it is built in the DockerHub :)

**Comment by cmourizard** [comment]
Perfect, as usual @dduportal !
Thanks a lot!

**Comment by dduportal** [comment]
OK on Dockerhub : https://hub.docker.com/r/dduportal/docker-compose/tags/
