### ISSUE TITLE
doesn't read yml file properly

### ISSUE THREAD

**Issue by phazei** [dduportal-dockerfiles/docker-compose#7]
When I try to run docker-compose, it gives errors as if the file were truncated as well as invalid #x0000 characters when the file is nothing but ascii.
I'm running it under windows, but it gives the same issues using the native windows docker.exe client, or boot2docker.

To test it I ran:

``` bash
docker run --rm -it -v /$(pwd)://app -v //var/run/docker.sock://var/run/docker.sock -e COMPOSE_PROJECT_NAME=$(basename $(pwd)) --entrypoint=//bin/sh  dduportal/docker-compose:latest
```

And I did a `cat docker-compose.yml` and it showed it as cut off.  When I viewed it in vi, it sometimes showed it all, other times didn't, was rather inconsistent.  Really peculiar.

I switched everything to use tatsushid/tinycore-python:2.7 as the base container.  Still very small, but now it works just fine.

Not a clue what could be wrong with Apline and the vboxsf file mounting.

**Comment by edmorley** [comment]
Ah - the base image was changed to alpine:3.2 (and also a switch from the docker-compose binary to the python package) on 29th May, in #2.

**Comment by dduportal** [comment]
Hello @phazei ! Thank you for pointing that out.

As i said in https://github.com/dduportal-dockerfiles/docker-compose/issues/6#issuecomment-111793904, i think it is related to sendfile system call that cause troubles with virtual box shared folders. I suppose that Linux Alpine base image has this behavior.

Switching the base image seems a good option but I want an "official"
Since Docker 1.7 will introduce new calls for the volumes sharing in remote mode, it may change some things. 

But i'm trying to revert to debian image to see if it works again with the current configs.

**Comment by dduportal** [comment]
OK, PR done and rebuilt the "latest" tag in the Docker Hub around "sendfile bug"

Could you please try again with the latest ? Do not forget to delete your local image to ensure you have the good version.

**Comment by dduportal** [comment]
I cannot reproduce with the latest one (1.3.0).

Can you try and reopen the issue if still reproducible on your side ?
